### ISSUE TITLE
I might be missing something in the docs but I am having problems with gulp

### ISSUE THREAD

**Issue by richtera** [rolandjitsu/ng2-lab#61]
I might be missing something in the docs, but when I try to run gulp it complains about

``` js
const {create} = require('browser-sync');
```

``` sh
> gulp -v
[16:27:16] CLI version 1.2.2
[16:27:16] Local version 4.0.0-alpha.2
> node -v
v5.12.0
```

Are these versions not correct?
Thanks
Andy

**Comment by rolandjitsu** [comment]
@richtera Not sure what is going on since you did not provide the error you got. There can be many things. I also haven't updated this in a while as I was quite busy.

I do plan a revamp with some upgrades for Angular 2 and other things.

But if you provide the error, I might be able to help.

Yes, the versions look good. You should install node 6 though, there are some bug fixes with that version and some ES6 features as well.

**Comment by rolandjitsu** [comment]
@richtera I'm closing this issue as I just moved the codebase to Angular CLI and a lot has changed.
